// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metadataSource': string;
  'name': string;
  'priority': string;
}
export const cssExports: CssExports;
export default cssExports;
